#!/usr/bin/env python3
"""
ipynb_to_py.py

Usage:
    python ipynb_to_py.py path/to/notebook.ipynb [-o path/to/output.py]

Converts a Jupyter notebook (.ipynb) into a Python script:
- Code cells become regular Python code.
- Markdown cells become commented lines.
"""

import argparse
import json
import os
import sys

def read_notebook(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        sys.exit(f"Error: file not found: {path}")
    except json.JSONDecodeError as e:
        sys.exit(f"Error: not a valid .ipynb JSON file ({e})")

def to_text(source):
    # 'source' may be a list of lines or a single string
    if isinstance(source, list):
        return "".join(source)
    return str(source)

def markdown_to_comments(text):
    # Prefix each line with '# ' (including blank lines)
    lines = text.splitlines()
    if not lines:
        return "#\n"
    return "".join(f"# {line}\n" if line.strip() else "#\n" for line in lines)

def infer_output_path(ipynb_path):
    base, ext = os.path.splitext(ipynb_path)
    return base + ".py"

def convert(ipynb_path, py_path):
    nb = read_notebook(ipynb_path)
    cells = nb.get("cells", [])

    parts = []
    parts.append("# Generated from: {}\n".format(os.path.basename(ipynb_path)))
    parts.append("# Do not edit this file manually if you intend to re-export.\n\n")

    for i, cell in enumerate(cells, start=1):
        ctype = cell.get("cell_type", "")
        src = to_text(cell.get("source", ""))

        # Add a clear separator between cells
        parts.append(f"# ----- Cell {i} ({ctype}) -----\n")

        if ctype == "markdown":
            parts.append(markdown_to_comments(src))
            parts.append("\n")
        elif ctype == "code":
            # Write code exactly as-is
            parts.append(src)
            # Ensure a trailing newline after each code cell
            if not src.endswith("\n"):
                parts.append("\n")
            parts.append("\n")
        else:
            # Any other cell types get commented for safety
            parts.append(markdown_to_comments(src))
            parts.append("\n")

    text = "".join(parts)

    # Ensure parent directory exists
    os.makedirs(os.path.dirname(py_path) or ".", exist_ok=True)

    with open(py_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

def main():
    parser = argparse.ArgumentParser(description="Convert .ipynb to .py with Markdown as comments.")
    parser.add_argument("ipynb", help="Path to the input .ipynb file")
    parser.add_argument("-o", "--output", help="Path to the output .py file (defaults to same name)")
    args = parser.parse_args()

    ipynb_path = args.ipynb
    py_path = args.output or infer_output_path(ipynb_path)

    if not ipynb_path.lower().endswith(".ipynb"):
        sys.exit("Error: input file must have a .ipynb extension")

    convert(ipynb_path, py_path)
    print(f"Wrote {py_path}")

if __name__ == "__main__":
    main()
